### PR TITLE
[story/TP-101038] update dm-sql-finders to 3.2 and dependencies to our gems

### PR DESCRIPTION
**Pull request by Adam-Shafer**
adding sql-finders to the docker-compose file

additional files to view:
https://github.com/firespring/data_mapper/pull/4
https://github.com/firespring/dm-aggregates/pull/6
https://github.com/firespring/dm-constraints/pull/6
https://github.com/firespring/dm-core/pull/6
https://github.com/firespring/dm-do-adapter/pull/7
https://github.com/firespring/dm-migrations/pull/6
https://github.com/firespring/dm-mysql-adapter/pull/7
https://github.com/firespring/dm-noisy-failures/pull/6
https://github.com/firespring/dm-serializer/pull/6
https://github.com/firespring/dm-sql-finders/pull/1
https://github.com/firespring/dm-sqlite-adapter/pull/4
https://github.com/firespring/dm-timestamps/pull/6
https://github.com/firespring/dm-transactions/pull/5
https://github.com/firespring/dm-types/pull/6
https://github.com/firespring/dm-validations/pull/6

To test run the rspec tests in the dm-sql-finders directory using `bundle exec rspec`. All of the tests should be passing.

### CODE REVIEW

**Comment by mkeiser82** [comment]
reviewing

**Review by mkeiser82 — CHANGES_REQUESTED** [review]
There are quite a few `DM_VERSION     = '~> 1.3.0'.freeze` that need updated to `DM_VERSION     = '~> 1.3'.freeze` in the various Gemfile(s).

I also have quite a few outdated `Gemfile.3.2.2` files (in each repo).  Those files are not under version control.  They appear to be used by the thor tasks.  What information do you have about those files?  Should we be using thor tasks for testing?

Please provide instruction for setup and/or update the readme as appropriate.  E.g. should `dm_mysql_finders` be added to the `DM_DEV_INCLUDE` env? Or the repo manually cloned etc.

Please provide general instructions for testing your changes.  I.e. what commands should be working and be tested. What test suites are functioning and should be ran. Etc.

Please provide very specific details and instructions for your changes on dm-migrations, dm-do-adapter, and dm-aggregates.  There may be a better way to handle those, but I will need specifics on what you were seeing and how to test changes.

**Comment by Adam-Shafer** [comment]
@mkeiser82 Working on these

1. Will update those and let you know when that is done.
2. Those are deleted when the publish command is ran or thor dm:bundle:force will also delete them. they get recreated when running dm:bundle:install. There looks to maybe be an issue with that at the moment most likely related to issue 1
3. That should probably just be added to the DM_DEV_INCLUDE env variable. That variable defines what repos get pulled/branches created when running the setup command. I added that in and just ran the command to pull it and set it up.
4. will add to the PR description
5. Will go add in those repos descriptions

I will slack you when this is ready for another look. Let me know if you have anymore questions

**Comment by mkeiser82** [comment]
Just making a note of whats left:
We need to add dm-sql-finders to `DM_DEV_INCLUDE` in the .env.
We also need the changes we discussed for https://github.com/firespring/dm-do-adapter/pull/7#pullrequestreview-2509796672 and https://github.com/firespring/dm-aggregates/pull/6#pullrequestreview-2509798817

**Comment by mkeiser82** [comment]
LGTM

**Pull request closed without merging**
